### ISSUE TITLE
Crash on startup, Java 17

### ISSUE THREAD

**Issue by rektuiemforameme** [Minecraft-Java-Edition-Speedrunning/mcsr-antiresourcereload-1.16.1#4] opened 2024-02-08 02:20 UTC
### Version
4.0.0

### Reproduction Steps
1. Put version 4.0.0 in the mods folder
2. Try to start Minecraft Java 1.16.1 with Java 17 from the Minecraft Launcher
3. It crashes
4. Replace 4.0.0 with version 1.2.1
6. It runs

### Crash Report File
[latest.log](https://github.com/Minecraft-Java-Edition-Speedrunning/mcsr-antiresourcereload-1.16.1/files/14203510/latest.log)

### Additional Information
My setup:
Windows 11, i7, 32gb ram
MC Java 1.16.1, Fabric 0.15.6
openjdk 17.0.7

I haven't tested with other Java versions. I know the mod version 1.2.1 that I got from https://github.com/faluhub/antiresourcereload works for me.

**Comment by tildejustin** [comment] 2024-02-11 19:06
you're still launching with java 8, you need to change the java version you're using for that instance in it's settings to java 17. that being said, this is a duplicate of #2 and needs to be fixed in the gradle buildscript.

**Closed by tildejustin** 2024-02-11 19:06 UTC

**Comment by rektuiemforameme** [comment] 2024-02-11 21:16
Damn, you're right. My bad for not checking the log more thoroughly or I would have seen that. This was a clean install of fabric, so I have no clue why it used java 8 instead of 17, which is the active version on my pc.

Confirmed, specifying java 17 in the settings resolved the issue. Thanks.
